from abc import ABC

class GameObjectBase(ABC):
    def Activate(self): ...
    def DeActivate(self): ...
    def IsActive(self) -> bool: ...
    
    def Draw(self): ...
    # def _OnUpdate(self): ...
    # def _OnPhysicsUpdate(self): ...
    
    def Update(self, deltatime : float): ...
    def PhysicsUpdate(self, tickTime : float): ...