from abc import ABC

class GameObjectBase(ABC):
    def Activate(self): ...
    def DeActivate(self): ...
    def IsActive(self): ...
    
    def Draw(self): ...
    def _OnUpdate(self): ...
    
    def Update(self): ...