from abc import ABC
import random
class GameObjectBase(ABC):
    def Activate(self): ...
    def DeActivate(self): ...
    def IsActive(self) -> bool: ...
    
    def Draw(self): ...
    def BeginPlay(self): ...
    # def _OnUpdate(self): ...
    # def _OnPhysicsUpdate(self): ...
    
    def Update(self, deltatime : float): ...
    def PhysicsUpdate(self, tickTime : float): ...


class LNL_IDGenerator:
    _current_id = 0

    @classmethod
    def get_id(cls):
        cls._current_id += 1
        return cls._current_id

    @classmethod
    def random_id(cls):
        return random.randint(0, cls._current_id)
