import pygame
from ApplicationEngine.src.Event.EventHandler import *

KEY_MAP = {
    'space': 32,
    'left': 37,
    'up': 38,
    'right': 39,
    'down': 40,
    '0': 48,
    '1': 49,
    '2': 50,
    '3': 51,
    '4': 52,
    '5': 53,
    '6': 54,
    '7': 55,
    '8': 56,
    '9': 57,
    'A': 65,
    'B': 66,
    'C': 67,
    'D': 68,
    'E': 69,
    'F': 70,
    'G': 71,
    'H': 72,
    'I': 73,
    'J': 74,
    'K': 75,
    'L': 76,
    'M': 77,
    'N': 78,
    'O': 79,
    'P': 80,
    'Q': 81,
    'R': 82,
    'S': 83,
    'T': 84,
    'U': 85,
    'V': 86,
    'W': 87,
    'X': 88,
    'Y': 89,
    'Z': 90,
    'a': 65,
    'b': 66,
    'c': 67,
    'd': 68,
    'e': 69,
    'f': 70,
    'g': 71,
    'h': 72,
    'i': 73,
    'j': 74,
    'k': 75,
    'l': 76,
    'm': 77,
    'n': 78,
    'o': 79,
    'p': 80,
    'q': 81,
    'r': 82,
    's': 83,
    't': 84,
    'u': 85,
    'v': 86,
    'w': 87,
    'x': 88,
    'y': 89,
    'z': 90
        }

_KeysInitState = {
            32 : False,
            37 : False,
            38 : False,
            39 : False,
            40 : False,
            48 : False,
            49 : False,
            50 : False,
            51 : False,
            52 : False,
            53 : False,
            54 : False,
            55 : False,
            56 : False,
            57 : False,
            65 : False,
            66 : False,
            67 : False,
            68 : False,
            69 : False,
            70 : False,
            71 : False,
            72 : False,
            73 : False,
            74 : False,
            75 : False,
            76 : False,
            77 : False,
            78 : False,
            79 : False,
            80 : False,
            81 : False,
            82 : False,
            83 : False,
            84 : False,
            85 : False,
            86 : False,
            87 : False,
            88 : False,
            89 : False,
            90 : False,
            65 : False,
            66 : False,
            67 : False,
            68 : False,
            69 : False,
            70 : False,
            71 : False,
            72 : False,
            73 : False,
            74 : False,
            75 : False,
            76 : False,
            77 : False,
            78 : False,
            79 : False,
            80 : False,
            81 : False,
            82 : False,
            83 : False,
            84 : False,
            85 : False,
            86 : False,
            87 : False,
            88 : False,
            89 : False,
            90 : False
    }


class Keys:
    _KEYS = {}

    @staticmethod
    def GetPressed():
        ...
    
    @staticmethod
    def _OnEvent(event : Event):
        if event.GetName() == "KeyDown":
            Keys._KEYS[event.keycode] = True
        if event.GetName() == "KeyUp":
            Keys._KEYS[event.keycode] = False

    @classmethod
    def Init(cls):
        cls._KEYS = _KeysInitState
        AddEventListener(cls._OnEvent)
